---
title: "Connon3"
author: "Leslie"
date: "September 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_pkgs, message=FALSE, warning=FALSE, results = 'hide', include=FALSE}

library(install.load)
install_load("tidyverse","janitor","lubridate","purrr","stringr", "readr", "dplyr", "tidyr", "readxl", "data.table", "tidyselect", "knitr","kableExtra", "parsedate","rio","stringi","stringr","ggplot2","grid","gtable") # list packages needed
```

```{r data_locations}
unit_csv <- 'raw_data/unit_raw.csv'
revenue_csv <- 'raw_data/revenue_raw_17.csv'
state_csv <- 'raw_data/state_raw.csv'
```

```{r read_in}
unit_raw <- read_csv(unit_csv) %>% clean_names()
revenue_raw <- read_csv(revenue_csv) %>% clean_names()
state_raw <- read_csv(state_csv) %>% clean_names()
```

```{r}

revenue_clean <- revenue_raw %>% 
  filter(crm!=0) %>% 
  mutate(start=y1701 + 
               y1702 +
               y1703 + 
               y1704 +
               y1705 + 
               y1706 +
               y1707) %>% 
  mutate(end=  y1801 + 
               y1802 +
               y1803 + 
               y1804 +
               y1805 + 
               y1806 +
               y1807) %>% 
  mutate(start2=y1601 + 
               y1602 +
               y1603 + 
               y1604 +
               y1605 + 
               y1606 +
               y1607 +
               y1608 + 
               y1609 +
               y1610 +
               y1611 +
               y1612 ) %>%
  mutate(end2=y1701 + 
               y1702 +
               y1703 + 
               y1704 +
               y1705 + 
               y1706 +
               y1707 +
               y1708 + 
               y1709 +
               y1710 +
               y1711 +
               y1712 ) 
```

```{r}

state <- state_raw %>% 
  select(crm=member_id, state)

rev_call <- revenue_clean %>% 
  left_join(state, by= "crm")%>%
  select(crm,start,end,end2,start2,state) %>% 
mutate(state=trimws(state)) %>% 
  
  mutate(hum=ifelse(state=="Arizona"|
                    state=="Arkansas"|
                    state=="Nevada"|
                    state=="Ohio"|
                    state=="Oklahoma"|
                    state=="Texas"|
                    state=="Washington",
              "old",
             ifelse(state=="Alabama"|
                    state=="Colorado"|
                    state=="Georgia"|
                    state=="Idaho"|
                    state=="Illinois"|
                    state=="Indiana"|
                    state=="Iowa"|
                    state=="Kansas"|
                    state=="Kentucky"|
                    state=="Louisiana"|
                    state=="Michigan"|
                    state=="Minnesota"|
                    state=="Mississippi"|
                    state=="Missouri"|
                    state=="Montana"|
                    state=="Nebraska"|
                    state=="New Mexico"|
                    state=="North Carolina"|
                    state=="North Dakota"|
                    state=="Oregon"|
                    state=="Pennsylvania"|
                    state=="South Carolina"|
                    state=="South Dakota"|
                    state=="Utah"|
                    state=="Virginia"|
                    state=="West Virginia"|
                    state=="Wisconsin",
              "new", "untouched"))) %>% 
mutate(GR2018=(end/start)-1) %>% 
mutate(GR2017=(end2/start2)-1) %>%
  filter(!is.na(hum))



old_new <- rev_call %>% 
  filter(hum=="new"|hum=="old")
t.test(GR2018 ~ hum,old_new )

old_untouched <- rev_call %>% 
  filter(hum=="untouched"|hum=="old")
t.test(GR2018 ~ hum, old_untouched )

new_untouched <- rev_call %>% 
  filter(hum=="new"|hum=="untouched")
t.test(GR2018 ~ hum, new_untouched )


sum1 <- rev_call %>% 
  group_by(hum) %>% 
  summarise(number = n(),GR2018 = mean(GR2018),GR2017 = mean(GR2017)) %>% 
 

sum2 <- rev_call %>% 
  summarise(number = n(),GR2018 = mean(GR2018),GR2017 = mean(GR2017))
            
rev_17_final<- rev_hum %>%        
select(hum,total_month,weight) %>% 
  group_by(hum) %>% 
  summarise(sum_grow = sum(weight),sum_month=sum(total_month)) %>% 
  mutate(rate=sum_grow/(sum_month/12))
  
  
```
